### ISSUE TITLE
[Formulários Site] - Termos & Condições e Conclusão da Inscrição

### ISSUE THREAD

**Issue by IsabellaMaciel** [SouJunior/site-backend#10]
---
name: User Story - Site
about: User Story do Produto "Site".
title: "[US SITE]"
labels: ''
assignees: ''

US de referência: [Reestruturação do Formulário para Juniores - Site](https://github.com/SouJunior/site-webapp/issues/232)

---
___________________________________________________________________________________________________________

**Definição**

Como candidato, eu desejo preencher todos os campos obrigatórios e aceitar os termos e condições de maneira fácil e rápida para concluir minha inscrição no processo seletivo da SouJunior.

___________________________________________________________________________________________________________

**Descrição**

A User Story detalha o procedimento necessário para concluir a inscrição do formulário para Juniores, envolvendo o preenchimento dos campos obrigatórios, a concordância com os termos e condições, e a verificação de todas as seleções requeridas para finalizar o processo de inscrição.

___________________________________________________________________________________________________________

**Protótipos**

https://www.figma.com/design/tB2QJPPRgojSvLf2Y4gGBX/Formul%C3%A1rio-SouJunior?node-id=92-4709&t=JNaj8cxUZgd74PRg-1

![Image](https://github.com/SouJunior/site-backend/assets/31568030/c8524834-61c1-4716-b8fd-325cf9f6cd4c)

___________________________________________________________________________________________________________

Critérios de Aceite

1. O usuário acessa o site da SouJunior.

2. Ao clicar em "Faça parte", o usuário é direcionado para a seção "Faça você também parte da nossa comunidade!".

3. Ao clicar na seção "Sou Junior", o usuário pode ler a descrição.

4. Ao clicar no botão "Quero Participar", o usuário é redirecionado para outra página para iniciar sua inscrição.

5. Na página de inscrição, o usuário só pode finalizá-la ao preencher todos os campos obrigatórios e concordar com os termos e condições, marcando os checkboxes correspondentes.

6. Se o usuário aceitar os termos, um pop-up exibirá o texto completo para revisão antes da finalização da inscrição.

7. O botão "Enviar" só será ativado quando todos os campos obrigatórios estiverem preenchidos, o usuário aceitar o checkbox "Estou de acordo com os Termos e Condições", e o checkbox "Declaro que as informações fornecidas são verdadeiras e autorizo a SouJunior a me contatar".

8. Ao marcar o checkbox "Estou de acordo com os Termos e Condições", um pop-up será exibido com o texto completo dos termos.

9. O pop-up incluirá um botão fixo "Li e concordo", que só será ativado após o usuário ao fim do documento.

10. Ao fim do documento, deverá selecionar o botão "Li e concordo". Após essa ação, o pop-up será fechado e a caixa de seleção no formulário para juniores será marcada automaticamente.

11. Caso o usuário desmarque a caixa de seleção e a selecione novamente, será necessário repetir o processo de leitura dos termos e condições.

___________________________________________________________________________________________________________

**Informações Adicionais**

[Termos e Condições - Formulário Site](https://docs.google.com/document/d/1throQ4s-dfp4VbMD-Yw49hHjFzMourKOZ40p46uWLYE/edit?usp=sharing)

___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by IsabellaMaciel** [comment]
Oi, @TayTeixeira! Analisarei toda a US com calma, mas antes de prosseguir, gostaria de discutir alguns pontos com você:

**1 - Definição:** "Como usuário, eu desejo **preencher todos os campos obrigatórios** e **aceitar os termos e condições** para concluir minha inscrição na SouJunior."

Você fingindo que é esse usuário, se colocando no lugar dele, o que você mais deseja? Acredito que sua resposta seja algo próximo a "Não, quero só concluir minha inscrição".

Partindo desse princípio, como você acredita que essa parte poderia ser melhor elaborada para demonstrar a real necessidade apresentada na US?

**2 - Descrição:** "A User Story destaca o procedimento de inscrição na plataforma SouJunior, onde os usuários **devem completar os campos obrigatórios e concordar com os termos e condições** para concluir o processo de inscrição."

Então a US não trata apenas dos termos de uso? Trata tbm dos campos obrigatórios? São é isso que o título indica.

**3 - Protótipos:** "Wireframes ou **fluxgramas** que representem visualmente a User Story descrita."

Cuidado com a grafia, sugiro a utilização de uma extensão gratuita que auxilia bastante: https://languagetool.org/pt-BR/services

O que acha dessas questões?

-----------------

PS: Depois analisarei os demais pontos, se precisar de ajuda, não hesite em me chamar.

**Comment by TayTeixeira** [comment]
Ei @IsabellaMaciel! Fiz as correções dos campos que você solicitou, poderia verificar novamente por favor?

**Comment by TayTeixeira** [comment]
Realizei as alterações conforme suas observações 1, 2, 3, 4, 5 e 6. Poderia revisá-las, por favor?

Sobre as observações 7 e 8, o DoD e DoR são do template, e não cheguei a modificá-los.

A observação 9 já discutimos anteriormente.

**Comment by IsabellaMaciel** [comment]
@TayTeixeira Agradeço pelas alterações, estou de acordo, pode prosseguir.

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
