### ISSUE TITLE
(Backend) Reestruturação do Formulário para Juniores

### ISSUE THREAD

**Issue by sabrinamir** [SouJunior/site-backend#15]
---
name: Reestruturação do Formulário para Juniores - Site
about: User Story do Produto "Site".
title: "[Reestruturação do Formulário para Juniores - Site]"
labels: ''
assignees: ''

---
___________________________________________________________________________________________________________

**Definição**

Como candidato, desejo me inscrever no formulário de processo seletivo para Juniores da SouJunior, para que possa competir por uma vaga e participar de projetos reais, buscando adquirir experiência para entrar e/ou se destacar no mercado.

___________________________________________________________________________________________________________

**Descrição**

Esta User Story aborda a necessidade de duas squads da SouJunior, a do Site e a do Backoffice RH, que estão colaborando para reestruturar o formulário para Juniores. O objetivo é satisfazer tanto as necessidades dos candidatos, que desejam mais feedback do processo seletivo, quanto as do RH da SouJunior, que precisa de dados para realizar um ranqueamento eficiente dos novos candidatos. Como parte dessa iniciativa, também será desenvolvida uma página com a identidade visual da SouJunior. Nessa primeira etapa, a V1, estamos focando na reestruturação do formulário.

___________________________________________________________________________________________________________

**Protótipos**
Wireframes ou fluxogramas que representem visualmente a User Story descrita.

https://www.figma.com/design/tB2QJPPRgojSvLf2Y4gGBX/Formul%C3%A1rio-SouJunior?node-id=12-3981&t=H94NStKsPWW4kltB-1

___________________________________________________________________________________________________________

**Critérios de aceite**

1. O usuário entrará no site da SouJunior.

2. O usuário irá clicar em "Faça parte" e será direcionado para a seção "Faça você também parte da nossa comunidade!".

3. Ao clicar na seção "Sou Junior", o usuário terá acesso à descrição da seção.

4. Ao clicar no botão "Quero Participar", o usuário será redirecionado para outra página para fazer sua inscrição.
 
5. O usuário deverá informar o nome completo.
- *Campo obrigatório*

6. O usuário deverá informar o e-mail.
- Para ser considerado um e-mail válido, ele deve conter o símbolo de @ + o domínio do e-mail + .com/.net/.br.
- *Campo obrigatório*

7. Caso o e-mail não siga os critérios de validação, o sistema deverá apresentar uma mensagem abaixo do campo com a descrição: "E-mail inválido."

8. O usuário deve preencher o campo LinkedIn.
- *Campo obrigatório*

9. O campo "A SouJunior realiza reuniões e atividades no período noturno. Você tem disponibilidade para atuar nesse turno?˜, deve escolher apenas uma opção.
- *Campo obrigatório*
- ( ) Sim
- ( ) Não

10. O campo "Quanto tempo você poderia dedicar por semana ao voluntariado?" deve ser de múltipla escolha. Ele terá 4 opções, onde o usuário poderá escolher apenas uma:
- *Campo obrigatório*
- ( ) Até 5 horas
- ( ) 5 a 10 horas
- ( ) Mais de 10 horas

11. Caso o usuário não selecione nenhuma opção no campo "Quanto tempo você poderia dedicar por semana ao voluntariado?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

12. O campo "Qual a sua disponibilidade para início?" deve ser de múltipla escolha. Ele terá 3 opções, onde o usuário poderá escolher apenas uma e a 3ª opção será aberta caso nenhuma das outras opções responda à situação do usuário:
- *Campo obrigatório*
- ( ) Imediato
- ( ) Dentro de 30 dias
- ( ) Outro: ___________

13. O campo "Qual das opções abaixo seria sua área de interesse?˜, terá as áreas de atuação da SouJunior, onde o usuário só poderá escolher uma opção.
*Campo obrigatório*
[Áreas de Atuação]
- ( ) Produto
- ( ) Design
- ( ) Agilidade
- ( ) Back-End
- ( ) Front-End
- ( ) Dados
- ( ) QA - Quality Assurance
- ( ) DevOps
- ( ) Tech Recruitment
- ( ) Business

14. Caso o usuário não selecione nenhuma opção no campo "Qual das opções abaixo seria sua área de interesse?", quando clicar em "Enviar", um aviso será exibido abaixo do campo, solicitando que ele assinale uma das opções para prosseguir: "Por favor, assinale uma das opções para prosseguir."

15. Ainda no campo "Qual das opções abaixo seria sua área de interesse?", se o usuário escolher a área de Produto, deverá aparecer opções de subáreas de Produto para o usuário selecionar apenas uma. 
*Campo obrigatório*
[Áreas de Produto]
- ( ) Product Growth
- ( ) Product OPS
- ( ) Product Marketing Manager
- ( ) Social Media 
- ( ) APM - Associate Product Manager

16. Ainda no campo "Qual das opções abaixo seria sua área de interesse?", se o usuário escolher a área de Design, deverá aparecer opções de subáreas de Produto para o usuário selecionar apenas uma. 
*Campo obrigatório*
[Áreas de Design]
- ( ) UX/UI
- ( ) Design Ops

17. No campo "Você tem conhecimento/experiência com ferramentas e tecnologias na área em que deseja atuar?", será uma pergunta aberta
- *Campo obrigatório*

18. No campo "Você já possui algum conhecimento prévio sobre os conceitos teóricos da área em que deseja atuar?˜, será uma pergunta aberta.
- *Campo obrigatório*

19. No campo "Antes de finalizarmos sua candidatura, há algum aspecto importante sobre sua motivação para se tornar voluntário na SouJunior?", o candidato deve responder uma pergunta aberta.
- *Campo obrigatório*

20. Caso os campos obrigatórios não forem preenchidos, ao clicar em "Enviar", aparecerá uma mensagem em vermelho no campo não preenchido: "O campo não foi preenchido."

21. Após o último campo, terá um botão: "Enviar", que só será ativado quando o usuário preencher todos os campos e aceitar os termos e condições. _`(O texto dos termos e condições será definido em uma outra US).`_

22. Quando o usuário clicar em "Enviar", aparecerá um pop-up com a mensagem: "Inscrição concluída. Você receberá um e-mail de confirmação em breve.", e logo em seguida, será enviado um e-mail de confirmação da inscrição. _`(O texto do e-mail será definido em uma outra US).`_

23. Os dados do usuário deverão ser direcionados para uma planilha que será gerenciada pela Squad de Backoffice.

24. O usuário será redirecionado para a "home" após clicar em "Enviar".

25. Após clicar em "Voltar" ou em qualquer lugar que atualize a página, aparecerá um pop-up com um botão escrito: "Você deseja mesmo cancelar a inscrição?" com a opção "sim" e "não".

26. Caso o usuário opte por "sim", ele será redirecionado para a "home".

27. Caso o usuário opte por "não", os dados continuarão preenchidos e ele deverá clicar em "Enviar" para enviar a inscrição.

___________________________________________________________________________________________________________

**Informações Adicionais**

[Forms google exemplo](https://docs.google.com/forms/d/1XypJq0h8vNTq06c7W0wE4tkY7dGpXR48PyXy-CqnVX0/prefill)

___________________________________________________________________________________________________________

**DoR - Definition of Ready**
- [ ] O design/wireframe foi definido e aprovado.

- [ ] A tarefa foi priorizada de acordo com o backlog e com as necessidades.

- [ ]  Os critérios de aceite estão claramente definidos a serem executada pela equipe.

- [ ] As dependências do projeto foram identificadas e resolvidas e documentadas.

- [ ] A equipe entendeu e concordou com as definições de "pronto" para a tarefa.
___________________________________________________________________________________________________________

**DoD - Definition of Done**
- [ ] Todos os requisitos funcionais definidos foram implementados e testados.

- [ ] O site está em conformidade com as especificações.

- [ ] O site é responsivo e funciona em diferentes tamanhos de tela e dispositivos.

- [ ] O site é acessível para usuários com deficiência.

- [ ] O tempo de carregamento da página é aceitável.

- [ ] O código foi testado por meio de testes automatizados.

- [ ] Os testes de aceitação do usuário foram realizados com sucesso.

- [ ] O design do site está de acordo com as diretrizes definidas.

- [ ] O site é esteticamente atraente e fácil de usar.

- [ ] A documentação do código é completa e atualizada.

- [ ] A documentação do usuário está disponível e é fácil de usar.

- [ ] O site foi implantado com sucesso no ambiente de produção.

- [ ] As configurações do servidor foram realizadas conforme as especificações definidas pelo cliente.

**Comment by GabrielOliveira9400** [comment]
Merge para producao feito

**Comment by sabrinamir** [comment]
Processo arquivado devido a alteração para que Backoffice crie o formulário de uma forma diferente.
