### ISSUE TITLE
[FAQ - Back-End] - Correção de perguntas Voluntário Júnior - Mentor/Apoiador

### ISSUE THREAD

**Issue by TayTeixeira** [SouJunior/site-backend#16]
LINK DA US DE REFERÊNCIA: https://github.com/orgs/SouJunior/projects/9/views/1?filterQuery=faq&pane=issue&itemId=11852797

DESCRIÇÃO DA ALTERAÇÃO: Na página de FAQ, as perguntas destinadas aos mentores/apoiadores estão na seção de *voluntário*, enquanto as perguntas destinadas aos júniores (voluntário) estão na seção de *mentor/apoiador*.

EVIDÊNCIA:

**Faq Júnior na seção de Mentor/Apoiador**
![Image](https://github.com/SouJunior/products/assets/31568030/0850e7ba-fa9d-4471-b147-1f699d118e80)

**Faq  Mentor/Apoiador na seção de Júnior**
![Image](https://github.com/SouJunior/products/assets/31568030/4be26830-de96-415c-bb57-a4835d48e475)

SOLUÇÃO: Na página de FAQ, as perguntas destinadas aos juniores que atualmente estão na seção de mentor/apoiador devem ser realocadas para a seção de juniores (Voluntário). Da mesma forma, as perguntas que estão atualmente na seção de juniores (Voluntário), mas são destinadas aos mentor/apoiador, devem ser movidas para a seção de mentor/apoiador.

**Comment by sabrinamir** [comment]
@GabrielOliveira9400 você consegue validar esta US junto com os meninos?

**Comment by GabrielOliveira9400** [comment]
Validada

**Comment by CryslaineGomes** [comment]
Cenarios de testes:
[Cenarios FAQ #16.pdf](https://github.com/user-attachments/files/17082338/Cenarios.FAQ.16.pdf)
Evidências:
[Evidencias FAQ #16.pdf](https://github.com/user-attachments/files/17082339/Evidencias.FAQ.16.pdf)
Video 1:
https://github.com/user-attachments/assets/e33b9ff4-03ec-4119-afb9-2c2db96d3b59

Video 2:
